import { CollectionConfig } from 'payload'

export const MaxProEvent: CollectionConfig = {
  slug: 'max-pro-events',
  admin: {
    group: 'Subscription & Max Pro',
    useAsTitle: 'eventType',
    defaultColumns: ['user', 'eventType', 'status', 'createdAt'],
    description: 'This collection is a system for tracking personalized AI insights, warnings, or summaries generated by a backend engine for premium users.',
  },
  access: {
    read: ({ req: { user } }) => Boolean(user && user.collection === 'admin'),
    create: ({ req: { user } }) => Boolean(user && user.collection === 'admin'),
    update: ({ req: { user } }) => Boolean(user && user.collection === 'admin'),
    delete: ({ req: { user } }) => Boolean(user && user.collection === 'admin'),
  },
  fields: [
    {
      name: 'user',
      type: 'relationship',
      relationTo: 'users',
      required: true,
      index: true,
      admin: {
        description: 'The user this event is for.',
      }
    },
    {
      name: 'eventType',
      type: 'select',
      options: [
        { label: 'Devaluation Detected', value: 'devaluation_detected' },
        { label: 'Target Spend Insight', value: 'target_spend_insight' },
        { label: 'Missing Card Warning', value: 'missing_card_warning' },
        { label: 'Weekly Summary', value: 'weekly_summary' },
      ],
      required: true,
      index: true,
      admin: {
        description: 'The kind of insight generated: Devaluation Detected, Target Spend Insight, Missing Card Warning, Weekly Summary.',
      }
    },
    {
      name: 'status',
      type: 'select',
      options: [
        { label: 'Generated', value: 'generated' }, // Waiting to be notified
        { label: 'Notified', value: 'notified' },   // Notification sent
        { label: 'Dismissed', value: 'dismissed' }, // User dismissed it
        { label: 'Acted Upon', value: 'acted_upon' },// User took action
      ],
      required: true,
      defaultValue: 'generated',
      admin: {
        description: 'The lifecycle of this event. Generated (waiting to be sent), Notified (pushed to user), Dismissed (user swiped it away), Acted Upon (user clicked it and took action).',
      }
    },
    {
      name: 'priority',
      type: 'select',
      options: [
        { label: 'Low', value: 'low' },
        { label: 'Medium', value: 'medium' },
        { label: 'High', value: 'high' },
        { label: 'Critical', value: 'critical' },
      ],
      required: true,
      defaultValue: 'low',
      admin: {
        description: 'How urgent the notification is (low, medium, high, critical).',
      }
    },
    {
      name: 'engineJobId',
      type: 'text',
      admin: {
        description: 'An ID linking back to the backend service (FastAPI engine) that crunched the data to generate this specific insight. Very useful for debugging if an insight looks wrong.',
      }
    },
    {
      name: 'payload',
      type: 'json',
      admin: {
        description: 'A flexible JSON object that holds the actual data for the UI to render. (e.g., {"cardId": "123", "oldReward": "3%", "newReward": "1%"}).',
      }
    }
  ],
}
