/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admin: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    admin: Admin;
    otp: Otp;
    'gmail-connections': GmailConnection;
    statements: Statement;
    banks: Bank;
    roles: Role;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    admin: AdminSelect<false> | AdminSelect<true>;
    otp: OtpSelect<false> | OtpSelect<true>;
    'gmail-connections': GmailConnectionsSelect<false> | GmailConnectionsSelect<true>;
    statements: StatementsSelect<false> | StatementsSelect<true>;
    banks: BanksSelect<false> | BanksSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  phone?: string | null;
  authenticationProvider: 'email' | 'phone' | 'google';
  authenticationProviderId?: string | null;
  profileCompleted: boolean;
  income?: number | null;
  employmentType?:
    ('full_time' | 'part_time' | 'self_employed' | 'unemployed' | 'student' | 'retired' | 'other') | null;
  accountStatus: 'active' | 'pending' | 'suspended';
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: number;
  /**
   * Assigns permissions and access rights to this user
   */
  role?: (number | null) | Role;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin';
}
/**
 * Manage admin roles and their permissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * Unique role identifier (e.g., super_admin, admin, editor)
   */
  name: string;
  /**
   * Display name for the role
   */
  label: string;
  /**
   * Select permissions for this role.
   */
  permissions?:
    | (
        | '*'
        | '*.read'
        | '*.create'
        | '*.update'
        | '*.delete'
        | 'users.*'
        | 'users.create'
        | 'users.read'
        | 'users.update'
        | 'users.delete'
        | 'users.manage'
        | 'media.*'
        | 'media.create'
        | 'media.read'
        | 'media.update'
        | 'media.delete'
        | 'media.manage'
        | 'admin.*'
        | 'admin.create'
        | 'admin.read'
        | 'admin.update'
        | 'admin.delete'
        | 'admin.manage'
        | 'otp.*'
        | 'otp.create'
        | 'otp.read'
        | 'otp.update'
        | 'otp.delete'
        | 'otp.manage'
        | 'gmail-connections.*'
        | 'gmail-connections.create'
        | 'gmail-connections.read'
        | 'gmail-connections.update'
        | 'gmail-connections.delete'
        | 'gmail-connections.manage'
        | 'statements.*'
        | 'statements.create'
        | 'statements.read'
        | 'statements.update'
        | 'statements.delete'
        | 'statements.manage'
        | 'banks.*'
        | 'banks.create'
        | 'banks.read'
        | 'banks.update'
        | 'banks.delete'
        | 'banks.manage'
        | 'banks.publish'
        | 'roles.*'
        | 'roles.create'
        | 'roles.read'
        | 'roles.update'
        | 'roles.delete'
        | 'roles.manage'
      )[]
    | null;
  /**
   * Optional description of the role and its purpose
   */
  description?: string | null;
  /**
   * Inactive roles cannot be used
   */
  active?: boolean | null;
  protected?: boolean | null;
  /**
   * Hash of the role configuration for version tracking
   */
  configHash?: string | null;
  /**
   * Version number for optimistic locking
   */
  configVersion?: number | null;
  /**
   * Indicates if this role is managed by the system
   */
  systemManaged?: boolean | null;
  /**
   * Select which auth-enabled collections can see and assign this role. Leave empty for all auth collections.
   */
  visibleFor?: ('users' | 'admin')[] | null;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp".
 */
export interface Otp {
  id: number;
  identifier: string;
  channel: 'email' | 'phone';
  codeHash: string;
  salt: string;
  expiresAt: number;
  attempts?: number | null;
  maxAttempts?: number | null;
  lastSentAt: number;
  resendAt: number;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gmail-connections".
 */
export interface GmailConnection {
  id: number;
  user: number | User;
  gmailAddress: string;
  encryptedRefreshToken: string;
  tokenIv: string;
  tokenTag: string;
  scopes?: string | null;
  status: 'active' | 'revoked' | 'expired';
  connectedAt: string;
  lastRefreshedAt?: string | null;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statements".
 */
export interface Statement {
  id: number;
  user: number | User;
  source: 'gmail' | 'upload';
  issuer: string;
  /**
   * Gmail message ID of the source email
   */
  gmailMessageId?: string | null;
  attachmentFilename?: string | null;
  status: 'pending' | 'processing' | 'parsed' | 'error';
  errorMessage?: string | null;
  transactionCount?: number | null;
  totalAmount?: number | null;
  accountLast4?: string | null;
  periodStart?: string | null;
  periodEnd?: string | null;
  pdf?: (number | null) | Media;
  /**
   * Size of the PDF file in bytes
   */
  pdfSize?: number | null;
  parsedAt?: string | null;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks".
 */
export interface Bank {
  id: number;
  name: string;
  code: string;
  shortName?: string | null;
  country?: string | null;
  website?: string | null;
  logo?: (number | null) | Media;
  statementConfig?: {
    parserType?: ('dedicated' | 'generic' | 'ocr_llm') | null;
    statementEmailSenders?:
      | {
          email?: string | null;
          id?: string | null;
        }[]
      | null;
    statementSubjectPatterns?:
      | {
          pattern?: string | null;
          id?: string | null;
        }[]
      | null;
    passwordHint?: string | null;
  };
  dataSource?: ('bank_website' | 'mitc' | 'statement' | 'research') | null;
  lastVerifiedAt?: string | null;
  notes?: string | null;
  slug?: string | null;
  createdBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  lastModifiedBy?: {
    relationTo: 'admin';
    value: number | Admin;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'admin';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'otp';
        value: number | Otp;
      } | null)
    | ({
        relationTo: 'gmail-connections';
        value: number | GmailConnection;
      } | null)
    | ({
        relationTo: 'statements';
        value: number | Statement;
      } | null)
    | ({
        relationTo: 'banks';
        value: number | Bank;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'admin';
        value: number | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'admin';
        value: number | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  authenticationProvider?: T;
  authenticationProviderId?: T;
  profileCompleted?: T;
  income?: T;
  employmentType?: T;
  accountStatus?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  role?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp_select".
 */
export interface OtpSelect<T extends boolean = true> {
  identifier?: T;
  channel?: T;
  codeHash?: T;
  salt?: T;
  expiresAt?: T;
  attempts?: T;
  maxAttempts?: T;
  lastSentAt?: T;
  resendAt?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gmail-connections_select".
 */
export interface GmailConnectionsSelect<T extends boolean = true> {
  user?: T;
  gmailAddress?: T;
  encryptedRefreshToken?: T;
  tokenIv?: T;
  tokenTag?: T;
  scopes?: T;
  status?: T;
  connectedAt?: T;
  lastRefreshedAt?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "statements_select".
 */
export interface StatementsSelect<T extends boolean = true> {
  user?: T;
  source?: T;
  issuer?: T;
  gmailMessageId?: T;
  attachmentFilename?: T;
  status?: T;
  errorMessage?: T;
  transactionCount?: T;
  totalAmount?: T;
  accountLast4?: T;
  periodStart?: T;
  periodEnd?: T;
  pdf?: T;
  pdfSize?: T;
  parsedAt?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banks_select".
 */
export interface BanksSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  shortName?: T;
  country?: T;
  website?: T;
  logo?: T;
  statementConfig?:
    | T
    | {
        parserType?: T;
        statementEmailSenders?:
          | T
          | {
              email?: T;
              id?: T;
            };
        statementSubjectPatterns?:
          | T
          | {
              pattern?: T;
              id?: T;
            };
        passwordHint?: T;
      };
  dataSource?: T;
  lastVerifiedAt?: T;
  notes?: T;
  slug?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  permissions?: T;
  description?: T;
  active?: T;
  protected?: T;
  configHash?: T;
  configVersion?: T;
  systemManaged?: T;
  visibleFor?: T;
  createdBy?: T;
  lastModifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}